In [1]:
import numpy as np

In [2]:
import matplotlib.pyplot as pp

In [3]:
a = np.array([1,2,3,4,5])

In [4]:
a

array([1, 2, 3, 4, 5])

In [5]:
a.dtype

dtype('int64')

In [6]:
a = np.array([1,2,3,4,5],dtype=np.float64)

In [7]:
a

array([1., 2., 3., 4., 5.])

In [8]:
a.ndim, a.shape, a.size

(1, (5,), 5)

In [10]:
b= np.array([[1,2,3,4,5],[6,7,8,9,20]],dtype=np.float64)

In [11]:
b

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 20.]])

In [12]:
b.dtype, b.shape, b.ndim, b.size

(dtype('float64'), (2, 5), 2, 10)

In [14]:
c = np.zeros((3,3),'d')
c

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
c.dtype

dtype('float64')

In [17]:
np.empty((4,4),'d')

array([[6.94736915e-310, 4.64954513e-310, 0.00000000e+000,
        0.00000000e+000],
       [6.94720202e-310, 5.02034658e+175, 5.29171500e+174,
        3.06009535e-057],
       [1.13876726e-042, 1.76137884e-076, 1.47763641e+248,
        1.16096346e-028],
       [7.69165785e+218, 1.35617292e+248, 3.91538500e-061,
        1.72479271e-047]])

In [18]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [19]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [22]:
a = np.random.standard_normal((2,4))
b = np.random.standard_normal((2,4))

np.vstack([a,b])

array([[-0.90945125, -0.08322634, -1.99643734, -0.3941359 ],
       [ 1.76051885, -0.3077451 ,  1.36705493, -1.18332394],
       [ 0.80291028, -0.05155637,  1.19554081, -1.05315767],
       [ 0.73465844, -1.10279972, -0.67505653,  0.69916489]])

In [23]:
np.hstack([a,b])

array([[-0.90945125, -0.08322634, -1.99643734, -0.3941359 ,  0.80291028,
        -0.05155637,  1.19554081, -1.05315767],
       [ 1.76051885, -0.3077451 ,  1.36705493, -1.18332394,  0.73465844,
        -1.10279972, -0.67505653,  0.69916489]])

In [25]:
a.transpose()

array([[-0.90945125,  1.76051885],
       [-0.08322634, -0.3077451 ],
       [-1.99643734,  1.36705493],
       [-0.3941359 , -1.18332394]])

In [28]:
np.save('example.py',a)

In [31]:
a1 = np.load('example.py.npy')

a1

In [32]:
a1

array([[-0.90945125, -0.08322634, -1.99643734, -0.3941359 ],
       [ 1.76051885, -0.3077451 ,  1.36705493, -1.18332394]])