In [1]:
import numpy as np

In [2]:
v = np.linspace(0,10,5)

In [3]:
v[0]

0.0

In [4]:
v[1]

2.5

In [5]:
v[-1]

10.0

In [6]:
v[5]

IndexError: index 5 is out of bounds for axis 0 with size 5

In [8]:
vv = np.random.random((5,4))

In [9]:
vv[0,0]

0.12858232028462202

In [10]:
vv[4,3]

0.11325945647416424

In [11]:
ll = [[1,2,3],[4,5,6],[7,8,9]]

In [12]:
ll[1,2]

TypeError: list indices must be integers or slices, not tuple

In [14]:
ll[1][2]

6

In [15]:
v

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [16]:
v[2:4]

array([5. , 7.5])

In [17]:
vv[2:5,1]

array([0.22364019, 0.34869105, 0.64278353])

In [18]:
vv[2:5,1:2]

array([[0.22364019],
       [0.34869105],
       [0.64278353]])

In [19]:
vv[2:-1,:]

array([[0.25618313, 0.22364019, 0.06737319, 0.33170535],
       [0.31892992, 0.34869105, 0.96530668, 0.15748494]])

In [20]:
vv[:,::2]

array([[0.12858232, 0.97032443],
       [0.21828478, 0.472829  ],
       [0.25618313, 0.06737319],
       [0.31892992, 0.96530668],
       [0.20780825, 0.33273025]])

In [21]:
v2 = v[2:4]

In [22]:
v2[0] = 0

In [23]:
v

array([ 0. ,  2.5,  0. ,  7.5, 10. ])

In [24]:
v3 = v[2:4].copy()

In [25]:
v3[0] = 1

In [26]:
v3

array([1. , 7.5])

In [27]:
v

array([ 0. ,  2.5,  0. ,  7.5, 10. ])

In [28]:
v[[1,2,3]]

array([2.5, 0. , 7.5])

In [30]:
bool_index =v>0

In [31]:
v[bool_index]

array([ 2.5,  7.5, 10. ])

In [32]:
vv[vv>0.5] = vv[vv>.5]*2

In [33]:
vv

array([[0.12858232, 0.37734414, 1.94064885, 0.36258248],
       [0.21828478, 1.69169617, 0.472829  , 1.55622328],
       [0.25618313, 0.22364019, 0.06737319, 0.33170535],
       [0.31892992, 0.34869105, 1.93061335, 0.15748494],
       [0.20780825, 1.28556707, 0.33273025, 0.11325946]])